version: '3.6'

networks:
  gobarber-network:
    driver: bridge

services:
  gobarber-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - POSTGRESQL_HOST=gobarber-postgresql
      - MONGODB_HOST=gobarber-mongo
    depends_on:
      - gobarber-postgresql
      - gobarber-mongo
    networks:
      - gobarber-network
    links:
      - gobarber-postgresql
      - gobarber-mongo
    container_name: gobarber-api
    command: yarn dev
    ports:
      - 3333:3333

  gobarber-postgresql:
    image: bitnami/postgresql:latest
    container_name: gobarber-postgresql
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRESQL_DATABASE=${POSTGRESQL_NAME}
    ports:
      - '5432:5432'
    volumes:
      - /tmp/postgresql:/bitnami
    networks:
      - gobarber-network

  gobarber-mongo:
    image: bitnami/mongodb:latest
    container_name: gobarber-mongo
    restart: always
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_NAME=${MONGODB_NAME}
    ports:
      - '27017:27017'
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - gobarber-network
